modLoader = "javafml"
loaderVersion = "[38,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "justenoughkeys"
version = "${version}"
displayName = "Just Enough Keys"
authors = "starmun"
description = '''
Taking away your key conflicts.
'''
#logoFile = ""

[[dependencies.justenoughkeys]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.justenoughkeys]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"

